# Generated by Django 3.0.2 on 2020-02-01 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("insurance", "0001_initial"), ("customer", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("pending", "En attente"),
                            ("open", "Ouvert"),
                            ("closed", "Clos"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=7,
                        verbose_name="Status",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "signature_date",
                    models.DateField(verbose_name="Date de souscription"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_contract_set",
                        to="customer.Customer",
                        verbose_name="Adhérent",
                    ),
                ),
                (
                    "insurance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurer_contract_set",
                        to="insurance.Insurance",
                        verbose_name="Assurance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrat",
                "verbose_name_plural": "Contrats",
                "ordering": ("signature_date", "number"),
            },
        )
    ]
